name: Pari Santani
url: https://psantani.art
title: Pari Santani - Portfolio
subtitle: Typography / Print / Animation
description: |
  Heyy baby just go through and update these fields with whatever you want :)
heroImage:
  image: /assets/site/heroImage/image.jpg
  alt: >-
    Black and white drawing of a room with a creature at the window, from the
    nightmare research painting.
